# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAcrtuallymoreitems():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_acrtuallymoreitems(self):
    self.driver.get("https://solutions.covestro.com/en/products/?query=:relevance:countries:US:productTypes:Polycarbonate%20polyol:productTypes:Polyester%20polyol:productTypes:Polyether%20polyol:productTypes:Polyol")
    self.driver.set_window_size(1032, 877)
    self.driver.execute_script("window.scrollTo(0,1263)")
    self.driver.find_element(By.CSS_SELECTOR, ".a-button--link").click()
  
