# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFullworkflow():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fullworkflow(self):
    self.driver.get("https://solutions.covestro.com/en/products/?query=:relevance:countries:US")
    self.driver.set_window_size(1032, 877)
    self.driver.find_element(By.CSS_SELECTOR, ".m-cookie-layer__close").click()
    self.driver.find_element(By.CSS_SELECTOR, "#productTypes .m-filter-multiselect__item-link--main").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-filter-multiselect__item--level1-open .m-filter-multiselect__item:nth-child(37) > .a-input-checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-filter-multiselect__item--level1-open .a-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-table__row:nth-child(1) > .m-product-table__column-description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-table__row:nth-child(1) > .m-product-table__column-description > .m-table__description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".g-grid:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-table__row:nth-child(1) > .m-product-table__column-description > .m-table__description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-table__row:nth-child(1) .m-table__datasheet-wrapper:nth-child(1) .a-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-table__row:nth-child(1) .m-table__datasheet-wrapper:nth-child(2) .a-button").click()
  
